CREATE TABLE IF NOT EXISTS erp.plan_cuentas (
    id      SERIAL PRIMARY KEY,
    codigo  VARCHAR(20) NOT NULL UNIQUE,
    nombre  VARCHAR(150) NOT NULL,
    tipo    VARCHAR(20) NOT NULL,
    nivel   VARCHAR(1) NOT NULL DEFAULT 'D',
    nota    TEXT,
    activa  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_plan_cuentas_codigo ON erp.plan_cuentas(codigo);

-- Limpiar e insertar plan de cuentas estándar PyME Chile
TRUNCATE erp.plan_cuentas RESTART IDENTITY;

INSERT INTO erp.plan_cuentas (codigo, nombre, tipo, nivel, nota) VALUES

-- CLASE 1: ACTIVO
('1',           'ACTIVO',                                           'ACTIVO',     'A', NULL),
('1.1',         'ACTIVO CORRIENTE',                                 'ACTIVO',     'A', NULL),
('1.1.1',       'EFECTIVO Y EQUIVALENTES AL EFECTIVO',              'ACTIVO',     'A', 'NIIF PyME Sección 7'),
('1.1.1.01',    'Caja Moneda Nacional',                             'ACTIVO',     'D', NULL),
('1.1.1.02',    'Caja Moneda Extranjera',                           'ACTIVO',     'D', 'Expresar en CLP al TC del día'),
('1.1.1.03',    'Fondo Fijo (Caja Chica)',                          'ACTIVO',     'D', NULL),
('1.1.1.10',    'Banco Cuenta Corriente CLP',                       'ACTIVO',     'D', 'Una subcuenta por cada cuenta bancaria'),
('1.1.1.11',    'Banco Cuenta Corriente USD',                       'ACTIVO',     'D', 'Expresar en CLP al TC cierre'),
('1.1.1.20',    'Depósitos a Plazo hasta 90 días',                  'ACTIVO',     'D', 'Equivalente de efectivo si vence ≤90 días'),
('1.1.2',       'CUENTAS POR COBRAR COMERCIALES',                   'ACTIVO',     'A', 'NIIF PyME Sección 11'),
('1.1.2.01',    'Clientes Nacionales',                              'ACTIVO',     'D', NULL),
('1.1.2.02',    'Clientes Extranjeros',                             'ACTIVO',     'D', 'Moneda extranjera, TC cierre'),
('1.1.2.03',    'Documentos por Cobrar (Letras, Pagarés)',          'ACTIVO',     'D', NULL),
('1.1.2.04',    'Facturas por Cobrar Electrónicas (DTE)',           'ACTIVO',     'D', 'Facturas emitidas pendientes de cobro'),
('1.1.2.05',    'Cheques por Cobrar a Fecha',                       'ACTIVO',     'D', NULL),
('1.1.2.90',    '(-) Deterioro de Cuentas por Cobrar',             'ACTIVO',     'D', 'Cuenta correctora, saldo acreedor; NIIF PyME S.11'),
('1.1.3',       'OTRAS CUENTAS POR COBRAR',                        'ACTIVO',     'A', NULL),
('1.1.3.01',    'Anticipos a Proveedores',                          'ACTIVO',     'D', NULL),
('1.1.3.02',    'Préstamos a Empleados',                            'ACTIVO',     'D', NULL),
('1.1.3.03',    'Deudores Varios',                                  'ACTIVO',     'D', NULL),
('1.1.3.04',    'Cuentas por Cobrar Partes Relacionadas',           'ACTIVO',     'D', 'Revelar en notas NIIF; atención precios transferencia'),
('1.1.4',       'ACTIVOS POR IMPUESTOS CORRIENTES (SII)',           'ACTIVO',     'A', NULL),
('1.1.4.01',    'IVA Crédito Fiscal (CF)',                          'ACTIVO',     'D', 'Libro Compras; F29 línea CF'),
('1.1.4.02',    'IVA CF Activo Fijo (Ley 19.738 - CEAF)',          'ACTIVO',     'D', 'CF por compra AF recuperable en 6 cuotas F29'),
('1.1.4.03',    'PPM Pagos Provisionales Mensuales',                'ACTIVO',     'D', 'F29 cod.67/68; imputable a impuesto anual F22'),
('1.1.4.04',    'Retenciones de Honorarios a Recuperar',           'ACTIVO',     'D', 'Retención 10,75% honorarios recibidos; F22'),
('1.1.4.05',    'Impuesto Único de Segunda Categoría a Recuperar', 'ACTIVO',     'D', NULL),
('1.1.4.06',    'Remanente IVA Crédito Fiscal Período Anterior',   'ACTIVO',     'D', 'Remanente CF arrastrado mes anterior'),
('1.1.4.07',    'PPUA (Pagos Provisionales por Utilidades Absorbidas)', 'ACTIVO','D', 'Pérdida absorbe utilidad; art.31 N°3 LIR'),
('1.1.4.08',    'Impuesto Específico a Recuperar',                 'ACTIVO',     'D', 'Impuesto combustibles Ley 18.502 (cód.28) y CO2 Ley 20.780 (cód.35); recuperable transportistas/mineras'),
('1.1.4.09',    'Impuesto por Recuperar (F22 a devolver)',         'ACTIVO',     'D', 'Cuando saldo F22 resulta a favor del contribuyente'),
('1.1.5',       'INVENTARIOS',                                      'ACTIVO',     'A', 'NIIF PyME Sección 13; valorizado al menor de costo/VNR'),
('1.1.5.01',    'Mercaderías para la Venta',                        'ACTIVO',     'D', 'Comercio; método PMP o FIFO'),
('1.1.5.02',    'Materias Primas',                                  'ACTIVO',     'D', 'Industria/Construcción'),
('1.1.5.03',    'Materiales Auxiliares y Suministros',             'ACTIVO',     'D', NULL),
('1.1.5.04',    'Productos en Proceso',                             'ACTIVO',     'D', NULL),
('1.1.5.05',    'Productos Terminados',                             'ACTIVO',     'D', NULL),
('1.1.5.06',    'Existencias en Tránsito',                         'ACTIVO',     'D', 'Compras en camino, aún no recibidas'),
('1.1.5.07',    'Repuestos y Materiales de Mantención',            'ACTIVO',     'D', 'Si consumo > 12 meses puede ser AF'),
('1.1.5.90',    '(-) Obsolescencia y Deterioro de Inventarios',    'ACTIVO',     'D', 'Cuenta correctora; NIIF PyME S.13'),
('1.1.6',       'GASTOS PAGADOS POR ANTICIPADO',                   'ACTIVO',     'A', NULL),
('1.1.6.01',    'Seguros Pagados por Anticipado',                   'ACTIVO',     'D', NULL),
('1.1.6.02',    'Arriendos Pagados por Anticipado',                 'ACTIVO',     'D', NULL),
('1.1.6.03',    'Suscripciones y Licencias Pagadas por Anticipado','ACTIVO',     'D', NULL),
('1.1.6.04',    'Otros Gastos Pagados por Anticipado',             'ACTIVO',     'D', NULL),
('1.1.7',       'OTROS ACTIVOS CORRIENTES',                        'ACTIVO',     'A', NULL),
('1.1.7.01',    'Activos No Corrientes Mantenidos para la Venta',  'ACTIVO',     'D', 'NIIF PyME S.17 cuando se decide vender AF'),
('1.1.7.02',    'Otros Activos Corrientes',                        'ACTIVO',     'D', NULL),
('1.2',         'ACTIVO NO CORRIENTE',                             'ACTIVO',     'A', NULL),
('1.2.1',       'PROPIEDADES, PLANTA Y EQUIPO (PPE)',              'ACTIVO',     'A', 'NIIF PyME Sección 17; modelo costo'),
('1.2.1.01',    'Terrenos',                                         'ACTIVO',     'D', 'No se deprecia'),
('1.2.1.02',    'Edificios y Construcciones',                       'ACTIVO',     'D', 'Vida útil SII: 20-50 años'),
('1.2.1.03',    'Instalaciones y Mejoras a Inmuebles Arrendados',  'ACTIVO',     'D', 'Amortizar en plazo menor entre VU y contrato'),
('1.2.1.04',    'Maquinaria y Equipos de Producción',              'ACTIVO',     'D', NULL),
('1.2.1.05',    'Vehículos y Medios de Transporte',                'ACTIVO',     'D', 'Atención: IVA CF vehículos art.23 N°6 DL825'),
('1.2.1.06',    'Muebles y Enseres',                               'ACTIVO',     'D', NULL),
('1.2.1.07',    'Equipos de Computación y Tecnología',             'ACTIVO',     'D', 'VU SII: 3-6 años'),
('1.2.1.08',    'Equipos de Comunicación',                         'ACTIVO',     'D', NULL),
('1.2.1.09',    'Herramientas y Equipos Menores',                  'ACTIVO',     'D', NULL),
('1.2.1.10',    'Obras en Construcción (Activo en Curso)',         'ACTIVO',     'D', 'No depreciar hasta que entre en uso'),
('1.2.1.91',    '(-) Depreciación Acumulada Edificios',            'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.92',    '(-) Depreciación Acumulada Instalaciones',        'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.93',    '(-) Depreciación Acumulada Maquinaria',           'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.94',    '(-) Depreciación Acumulada Vehículos',            'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.95',    '(-) Depreciación Acumulada Muebles y Enseres',    'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.96',    '(-) Depreciación Acumulada Equipos Computación',  'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.97',    '(-) Depreciación Acumulada Otros PPE',            'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.1.98',    '(-) Deterioro Acumulado PPE',                     'ACTIVO',     'D', 'NIIF PyME S.27; cuenta correctora'),
('1.2.2',       'PROPIEDADES DE INVERSIÓN',                        'ACTIVO',     'A', 'NIIF PyME Sección 16'),
('1.2.2.01',    'Terrenos como Inversión',                         'ACTIVO',     'D', NULL),
('1.2.2.02',    'Edificios como Inversión',                        'ACTIVO',     'D', 'Valor razonable o costo según política'),
('1.2.2.91',    '(-) Depreciación Acumulada Prop. Inversión',      'ACTIVO',     'D', 'Solo si usa modelo costo'),
('1.2.3',       'ACTIVOS INTANGIBLES',                             'ACTIVO',     'A', 'NIIF PyME Sección 18'),
('1.2.3.01',    'Programas Computacionales (Software)',             'ACTIVO',     'D', 'VU SII: 3 años (depreciación acelerada posible)'),
('1.2.3.02',    'Licencias de Software',                           'ACTIVO',     'D', NULL),
('1.2.3.03',    'Marcas Comerciales',                              'ACTIVO',     'D', NULL),
('1.2.3.04',    'Patentes y Derechos de Propiedad Intelectual',    'ACTIVO',     'D', NULL),
('1.2.3.05',    'Goodwill / Plusvalía (Adquisición Negocios)',     'ACTIVO',     'D', 'NIIF PyME S.19; amortizar 10 años si VU indefinida'),
('1.2.3.06',    'Gastos de Organización y Puesta en Marcha',       'ACTIVO',     'D', 'Tributariamente amortizable; NIIF puede ser gasto'),
('1.2.3.91',    '(-) Amortización Acumulada Intangibles',          'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.3.92',    '(-) Deterioro Acumulado Intangibles',             'ACTIVO',     'D', 'Cuenta correctora'),
('1.2.4',       'INVERSIONES EN EMPRESAS RELACIONADAS',            'ACTIVO',     'A', 'NIIF PyME S.14/S.15'),
('1.2.4.01',    'Inversión en Filiales (Subsidiarias)',            'ACTIVO',     'D', 'Método de participación o costo'),
('1.2.4.02',    'Inversión en Coligadas',                          'ACTIVO',     'D', 'Método de participación (influencia significativa)'),
('1.2.4.03',    'Inversión en Joint Ventures',                     'ACTIVO',     'D', NULL),
('1.2.4.04',    'Inversión en Otras Empresas (sin control)',       'ACTIVO',     'D', 'NIIF PyME S.11; costo o VR'),
('1.2.5',       'ACTIVOS FINANCIEROS NO CORRIENTES',               'ACTIVO',     'A', NULL),
('1.2.5.01',    'Depósitos a Plazo mayor a 90 días',               'ACTIVO',     'D', NULL),
('1.2.5.02',    'Instrumentos Financieros a Largo Plazo',          'ACTIVO',     'D', NULL),
('1.2.5.03',    'Garantías Otorgadas a Largo Plazo',               'ACTIVO',     'D', NULL),
('1.2.6',       'CUENTAS POR COBRAR NO CORRIENTES',                'ACTIVO',     'A', NULL),
('1.2.6.01',    'Clientes Largo Plazo (>12 meses)',                'ACTIVO',     'D', NULL),
('1.2.6.02',    'Préstamos a Relacionados Largo Plazo',            'ACTIVO',     'D', NULL),
('1.2.7',       'ACTIVOS POR IMPUESTOS DIFERIDOS',                 'ACTIVO',     'A', 'NIIF PyME Sección 29'),
('1.2.7.01',    'Impuesto Diferido Activo',                        'ACTIVO',     'D', 'Diferencias temporarias deducibles'),
('1.2.8',       'OTROS ACTIVOS NO CORRIENTES',                     'ACTIVO',     'A', NULL),
('1.2.8.01',    'Gastos Pagados por Anticipado Largo Plazo',       'ACTIVO',     'D', NULL),
('1.2.8.02',    'Otros Activos No Corrientes',                     'ACTIVO',     'D', NULL),

-- CLASE 2: PASIVO
('2',           'PASIVO',                                          'PASIVO',     'A', NULL),
('2.1',         'PASIVO CORRIENTE',                                'PASIVO',     'A', NULL),
('2.1.1',       'CUENTAS POR PAGAR COMERCIALES',                   'PASIVO',     'A', NULL),
('2.1.1.01',    'Proveedores Nacionales',                          'PASIVO',     'D', NULL),
('2.1.1.02',    'Proveedores Extranjeros',                         'PASIVO',     'D', 'TC cierre'),
('2.1.1.03',    'Documentos por Pagar (Letras, Pagarés)',          'PASIVO',     'D', NULL),
('2.1.1.04',    'Facturas por Pagar (DTE recibidas)',              'PASIVO',     'D', NULL),
('2.1.1.05',    'Anticipos de Clientes',                           'PASIVO',     'D', 'Ingreso diferido hasta devengo'),
('2.1.2',       'OBLIGACIONES CON INSTITUCIONES FINANCIERAS',      'PASIVO',     'A', NULL),
('2.1.2.01',    'Préstamos Bancarios Corto Plazo',                 'PASIVO',     'D', NULL),
('2.1.2.02',    'Líneas de Crédito Utilizadas',                    'PASIVO',     'D', NULL),
('2.1.2.03',    'Sobregiros Bancarios',                            'PASIVO',     'D', NULL),
('2.1.2.04',    'Porción Corriente Deuda Largo Plazo',             'PASIVO',     'D', 'Reclasificación cuota próximos 12 meses'),
('2.1.2.05',    'Factoring (Facturas cedidas con responsabilidad)', 'PASIVO',    'D', NULL),
('2.1.2.06',    'Leasing Financiero - Porción Corriente',          'PASIVO',     'D', 'NIIF PyME S.20'),
('2.1.3',       'PASIVOS POR IMPUESTOS (SII)',                     'PASIVO',     'A', NULL),
('2.1.3.01',    'IVA Débito Fiscal (DF)',                          'PASIVO',     'D', 'Libro Ventas; F29'),
('2.1.3.02',    'IVA Retenciones (agente retenedor)',              'PASIVO',     'D', 'Retención 2da categoría, construcción, etc.'),
('2.1.3.03',    'Impuesto Único Trabajadores (Art.42 N°1 LIR)',    'PASIVO',     'D', 'Retención mensual; enterar SII hasta día 12'),
('2.1.3.04',    'Retenciones Honorarios (Art.42 N°2 LIR - 10,75%)','PASIVO',    'D', 'Retención a retener y enterar al SII'),
('2.1.3.05',    'Impuesto de Primera Categoría por Pagar',         'PASIVO',     'D', 'F22; 27% SA/SpA o 25% régimen propyme'),
('2.1.3.06',    'IVA Neto por Pagar',                              'PASIVO',     'D', 'Resultado neto mes DF-CF; F29'),
('2.1.3.07',    'Contribuciones de Bienes Raíces por Pagar',       'PASIVO',     'D', NULL),
('2.1.3.08',    'Patente Municipal por Pagar',                     'PASIVO',     'D', NULL),
('2.1.3.09',    'Impuesto de Timbres y Estampillas',               'PASIVO',     'D', '0,066% mensual créditos; 0,8% máximo'),
('2.1.4',       'REMUNERACIONES Y OBLIGACIONES LABORALES',         'PASIVO',     'A', NULL),
('2.1.4.01',    'Remuneraciones por Pagar',                        'PASIVO',     'D', NULL),
('2.1.4.02',    'Horas Extras por Pagar',                          'PASIVO',     'D', NULL),
('2.1.4.03',    'Bonos y Comisiones por Pagar',                    'PASIVO',     'D', NULL),
('2.1.4.04',    'Vacaciones por Pagar (Provisión)',                'PASIVO',     'D', 'Obligación devengada; NIIF PyME S.28'),
('2.1.4.05',    'Cotizaciones Previsionales por Pagar (AFP)',       'PASIVO',     'D', '10% + comisión AFP; enterar hasta día 13'),
('2.1.4.06',    'Cotizaciones Salud por Pagar (Isapre/Fonasa)',    'PASIVO',     'D', '7% mínimo legal'),
('2.1.4.07',    'Seguro de Cesantía por Pagar (AFC)',              'PASIVO',     'D', '0,6% trabajador + 2,4% empleador contrato indefinido'),
('2.1.4.08',    'Mutual de Seguridad / ACHS por Pagar',            'PASIVO',     'D', 'Seguro accidentes del trabajo Ley 16.744'),
('2.1.4.09',    'Indemnización por Años de Servicio (Provisión)',  'PASIVO',     'D', 'Si empresa tiene política de provisión'),
('2.1.4.10',    'Descuentos Voluntarios Trabajadores por Enterar', 'PASIVO',     'D', 'Cuotas sindicato, ahorro, etc.'),
('2.1.4.11',    'Finiquitos por Pagar',                            'PASIVO',     'D', NULL),
('2.1.5',       'OTRAS CUENTAS POR PAGAR',                        'PASIVO',     'A', NULL),
('2.1.5.01',    'Acreedores Varios',                               'PASIVO',     'D', NULL),
('2.1.5.02',    'Cuentas por Pagar Partes Relacionadas',           'PASIVO',     'D', 'Revelar en notas'),
('2.1.5.03',    'Dividendos por Pagar',                            'PASIVO',     'D', NULL),
('2.1.5.04',    'Retiros por Pagar (SRL / Empresas Individuales)', 'PASIVO',     'D', NULL),
('2.1.5.05',    'Ingresos Anticipados (Diferidos Corriente)',      'PASIVO',     'D', 'Devengar en período que corresponde'),
('2.1.6',       'PROVISIONES CORRIENTES',                          'PASIVO',     'A', 'NIIF PyME Sección 21'),
('2.1.6.01',    'Provisión Garantías Postventa',                   'PASIVO',     'D', NULL),
('2.1.6.02',    'Provisión Litigios y Contingencias',              'PASIVO',     'D', NULL),
('2.1.6.03',    'Provisión Devoluciones y Descuentos',             'PASIVO',     'D', NULL),
('2.1.6.04',    'Provisión Aguinaldos y Gratificaciones',          'PASIVO',     'D', 'Gratificación legal 25% / 4,75 IMM'),
('2.1.6.05',    'Otras Provisiones Corrientes',                    'PASIVO',     'D', NULL),
('2.2',         'PASIVO NO CORRIENTE',                             'PASIVO',     'A', NULL),
('2.2.1',       'OBLIGACIONES FINANCIERAS LARGO PLAZO',            'PASIVO',     'A', NULL),
('2.2.1.01',    'Préstamos Bancarios Largo Plazo',                 'PASIVO',     'D', NULL),
('2.2.1.02',    'Bonos por Pagar',                                 'PASIVO',     'D', NULL),
('2.2.1.03',    'Leasing Financiero - Porción No Corriente',       'PASIVO',     'D', NULL),
('2.2.1.04',    'Deudas con Accionistas/Socios Largo Plazo',       'PASIVO',     'D', 'Atención: préstamos de socios, normas SII'),
('2.2.2',       'PASIVOS POR IMPUESTOS DIFERIDOS',                 'PASIVO',     'A', 'NIIF PyME Sección 29'),
('2.2.2.01',    'Impuesto Diferido Pasivo',                        'PASIVO',     'D', 'Diferencias temporarias imponibles'),
('2.2.3',       'PROVISIONES NO CORRIENTES',                       'PASIVO',     'A', NULL),
('2.2.3.01',    'Provisión Indemnización Años de Servicio LP',     'PASIVO',     'D', 'Porción > 12 meses'),
('2.2.3.02',    'Provisión Desmantelamiento y Restauración',       'PASIVO',     'D', 'NIIF PyME S.21; si aplica'),
('2.2.3.03',    'Otras Provisiones No Corrientes',                 'PASIVO',     'D', NULL),
('2.2.4',       'INGRESOS DIFERIDOS NO CORRIENTES',                'PASIVO',     'A', NULL),
('2.2.4.01',    'Ingresos Anticipados Largo Plazo',                'PASIVO',     'D', NULL),
('2.2.4.02',    'Subvenciones de Gobierno Diferidas',              'PASIVO',     'D', 'NIIF PyME S.24; CORFO, SERCOTEC, FOGAPE'),
('2.2.5',       'OTRAS CUENTAS POR PAGAR NO CORRIENTES',           'PASIVO',     'A', NULL),
('2.2.5.01',    'Otras Cuentas por Pagar Largo Plazo',             'PASIVO',     'D', NULL),

-- CLASE 3: PATRIMONIO
('3',           'PATRIMONIO',                                      'PATRIMONIO', 'A', NULL),
('3.1',         'CAPITAL',                                         'PATRIMONIO', 'A', NULL),
('3.1.1.01',    'Capital Pagado (SpA / SA)',                       'PATRIMONIO', 'D', 'Escritura social; RUT empresa'),
('3.1.1.02',    'Capital Asignado (EIRL / SRL)',                   'PATRIMONIO', 'D', NULL),
('3.1.1.03',    '(-) Capital por Suscribir (Porción no pagada)',   'PATRIMONIO', 'D', 'Cuenta correctora; saldo deudor'),
('3.1.1.04',    'Aportes Pendientes de Formalización',             'PATRIMONIO', 'D', 'Regularizar con escritura'),
('3.2',         'OTRAS RESERVAS DE CAPITAL',                       'PATRIMONIO', 'A', NULL),
('3.2.1.01',    'Reserva Legal (SA - 10% hasta 20% Capital)',      'PATRIMONIO', 'D', 'Obligatoria SA; Ley 18.046'),
('3.2.1.02',    'Reserva por Revaluación de PPE',                  'PATRIMONIO', 'D', 'Si usa modelo revaluación NIIF PyME S.17'),
('3.2.1.03',    'Reserva por Diferencias de Conversión',           'PATRIMONIO', 'D', 'Operaciones en moneda extranjera'),
('3.2.1.04',    'Otras Reservas Estatutarias',                     'PATRIMONIO', 'D', NULL),
('3.3',         'RESULTADOS ACUMULADOS',                           'PATRIMONIO', 'A', NULL),
('3.3.1.01',    'Utilidades Acumuladas Ejercicios Anteriores',     'PATRIMONIO', 'D', NULL),
('3.3.1.02',    'Pérdidas Acumuladas Ejercicios Anteriores',       'PATRIMONIO', 'D', 'Saldo deudor; pérdida tributaria art.31 N°3'),
('3.3.1.03',    '(-) Dividendos Decretados',                       'PATRIMONIO', 'D', 'Cuenta correctora; saldo deudor'),
('3.3.1.04',    '(-) Retiros del Ejercicio (SRL / EIRL)',          'PATRIMONIO', 'D', 'Cuenta correctora; saldo deudor'),
('3.4',         'RESULTADO DEL EJERCICIO',                         'PATRIMONIO', 'A', NULL),
('3.4.1.01',    'Utilidad del Ejercicio',                          'PATRIMONIO', 'D', 'Se cierra al 31/12 contra Resultados Acumulados'),
('3.4.1.02',    'Pérdida del Ejercicio',                           'PATRIMONIO', 'D', 'Saldo deudor'),
('3.5',         'CORRECCIÓN MONETARIA (HISTÓRICO)',                'PATRIMONIO', 'A', NULL),
('3.5.1.01',    'Corrección Monetaria Acumulada (IPC)',             'PATRIMONIO', 'D', 'Art.41 LIR; empresas con contabilidad ajustada IPC'),

-- CLASE 4: INGRESOS
('4',           'INGRESOS',                                        'INGRESO',    'A', NULL),
('4.1',         'INGRESOS OPERACIONALES',                          'INGRESO',    'A', NULL),
('4.1.1',       'VENTAS DE BIENES',                                'INGRESO',    'A', 'NIIF PyME S.23; devengo cuando se transfiere control'),
('4.1.1.01',    'Ventas Afectas a IVA - Nacionales',              'INGRESO',    'D', 'DF; F29 y Libro de Ventas'),
('4.1.1.02',    'Ventas Exentas de IVA',                          'INGRESO',    'D', 'Art.12 DL825; Libro de Ventas col.exentas'),
('4.1.1.03',    'Ventas No Gravadas con IVA',                     'INGRESO',    'D', 'Art.8 DL825 excluidas'),
('4.1.1.04',    'Exportaciones (Ventas al Exterior)',              'INGRESO',    'D', 'Exentas IVA art.12 letra D; acreditar devolución IVA'),
('4.1.1.05',    '(-) Devoluciones y Descuentos sobre Ventas',     'INGRESO',    'D', 'Cuenta correctora; NC electrónicas'),
('4.1.2',       'INGRESOS POR SERVICIOS',                         'INGRESO',    'A', NULL),
('4.1.2.01',    'Servicios Afectos a IVA',                        'INGRESO',    'D', 'DF; Libro Ventas'),
('4.1.2.02',    'Servicios Exentos de IVA',                       'INGRESO',    'D', 'Ej. servicios médicos, educación art.12 E'),
('4.1.2.03',    'Honorarios (Boletas de Honorarios Electrónicas)', 'INGRESO',    'D', 'Sin IVA; afectos a retención o PPM voluntario'),
('4.1.2.04',    'Servicios de Construcción',                       'INGRESO',    'D', 'Afectos IVA; retención 35% en ciertos contratos'),
('4.1.2.05',    'Ingresos por Contratos de Construcción',         'INGRESO',    'D', 'NIIF PyME S.23 método avance de obra'),
('4.1.2.06',    '(-) Devoluciones y Descuentos sobre Servicios',  'INGRESO',    'D', 'Cuenta correctora'),
('4.1.3',       'OTROS INGRESOS OPERACIONALES',                   'INGRESO',    'A', NULL),
('4.1.3.01',    'Comisiones Ganadas',                              'INGRESO',    'D', NULL),
('4.1.3.02',    'Ingresos por Arrendamiento Operacional',          'INGRESO',    'D', 'Si es actividad principal'),
('4.1.3.03',    'Ingresos por Licencias y Regalías',              'INGRESO',    'D', NULL),
('4.2',         'INGRESOS NO OPERACIONALES',                       'INGRESO',    'A', NULL),
('4.2.1',       'INGRESOS FINANCIEROS',                            'INGRESO',    'A', NULL),
('4.2.1.01',    'Intereses Ganados (Cuentas Bancarias, DPF)',      'INGRESO',    'D', 'Afectos impuesto; declarar en F22'),
('4.2.1.02',    'Intereses Ganados de Clientes',                   'INGRESO',    'D', 'Afectos IVA si accesorio a operación afecta'),
('4.2.1.03',    'Dividendos Recibidos',                            'INGRESO',    'D', 'Crédito IDPC en F22; art.56 N°3 LIR'),
('4.2.1.04',    'Diferencias de Cambio Favorables',               'INGRESO',    'D', 'TC cierre; afecta base imponible'),
('4.2.2',       'OTROS INGRESOS NO OPERACIONALES',                 'INGRESO',    'A', NULL),
('4.2.2.01',    'Utilidad en Venta de Activo Fijo',               'INGRESO',    'D', 'Afecta renta; precio venta - VNT'),
('4.2.2.02',    'Utilidad en Venta de Inversiones',               'INGRESO',    'D', NULL),
('4.2.2.03',    'Ingresos por Indemnizaciones de Seguros',         'INGRESO',    'D', NULL),
('4.2.2.04',    'Recuperación de Gastos de Ejercicios Anteriores','INGRESO',    'D', NULL),
('4.2.2.05',    'Subvenciones y Subsidios del Estado',             'INGRESO',    'D', 'NIIF PyME S.24; SERCOTEC, CORFO'),
('4.2.2.06',    'Donaciones Recibidas',                            'INGRESO',    'D', 'Ley 19.885; tope deducción'),
('4.2.2.07',    'Otros Ingresos Extraordinarios',                  'INGRESO',    'D', NULL),
('4.3',         'CORRECCIÓN MONETARIA ACTIVOS',                    'INGRESO',    'A', NULL),
('4.3.1.01',    'Corrección Monetaria Activos (IPC)',              'INGRESO',    'D', 'Art.41 LIR; empresas con contabilidad ajustada'),

-- CLASE 5: COSTOS Y GASTOS
('5',           'COSTOS Y GASTOS',                                 'EGRESO',     'A', NULL),
('5.1',         'COSTO DE VENTAS Y SERVICIOS',                     'EGRESO',     'A', NULL),
('5.1.1',       'COSTO DE VENTAS - MERCADERÍAS',                  'EGRESO',     'A', NULL),
('5.1.1.01',    'Costo de Mercaderías Vendidas',                   'EGRESO',     'D', 'PMP o FIFO; según política contable'),
('5.1.1.02',    'Costo de Importación (Fletes, Seguros, Aduana)',  'EGRESO',     'D', 'Parte del costo del inventario'),
('5.1.1.03',    'Mermas y Deterioro de Inventarios',               'EGRESO',     'D', 'Mermas tributarias requieren prueba'),
('5.1.2',       'COSTO DE PRODUCCIÓN',                             'EGRESO',     'A', NULL),
('5.1.2.01',    'Materias Primas Consumidas',                      'EGRESO',     'D', NULL),
('5.1.2.02',    'Mano de Obra Directa',                            'EGRESO',     'D', NULL),
('5.1.2.03',    'Costos Indirectos de Fabricación (CIF)',          'EGRESO',     'D', 'Distribución por sistema de costeo'),
('5.1.2.04',    'Depreciación Maquinaria Producción',              'EGRESO',     'D', NULL),
('5.1.3',       'COSTO DE SERVICIOS Y CONTRATOS',                  'EGRESO',     'A', NULL),
('5.1.3.01',    'Subcontratos y Tercerización de Servicios',       'EGRESO',     'D', 'Atención: retención 35% construcción'),
('5.1.3.02',    'Materiales Incorporados en Servicios',            'EGRESO',     'D', NULL),
('5.1.3.03',    'Mano de Obra Directa Servicios',                  'EGRESO',     'D', NULL),
('5.1.3.04',    'Costos Directos de Contratos de Construcción',    'EGRESO',     'D', 'Avance de obra correlativo con ingreso S.23'),
('5.2',         'GASTOS DE ADMINISTRACIÓN Y VENTAS',               'EGRESO',     'A', NULL),
('5.2.1',       'REMUNERACIONES Y CARGAS SOCIALES',                'EGRESO',     'A', NULL),
('5.2.1.01',    'Sueldos y Salarios',                              'EGRESO',     'D', 'Gasto tributario art.31 N°1 LIR'),
('5.2.1.02',    'Horas Extras',                                    'EGRESO',     'D', NULL),
('5.2.1.03',    'Bonos y Gratificaciones',                         'EGRESO',     'D', 'Gratificación legal o contractual'),
('5.2.1.04',    'Comisiones a Vendedores',                         'EGRESO',     'D', NULL),
('5.2.1.05',    'Honorarios a Personas Naturales',                 'EGRESO',     'D', 'Retención 10,75%; BHE electrónica'),
('5.2.1.06',    'Honorarios a Empresas',                           'EGRESO',     'D', 'Sin retención; atención precio de transferencia'),
('5.2.1.07',    'Cotizaciones Previsionales Empleador (AFP)',       'EGRESO',     'D', '2,4% cesantía + SIS'),
('5.2.1.08',    'Cotizaciones Seguro Cesantía Empleador (AFC)',    'EGRESO',     'D', NULL),
('5.2.1.09',    'Seguro Accidentes del Trabajo (Mutual/ACHS)',     'EGRESO',     'D', 'Tasa base 0,93% + adicional por actividad'),
('5.2.1.10',    'Indemnización por Años de Servicio',              'EGRESO',     'D', 'Gasto año desvinculación; art.31 N°8 LIR'),
('5.2.1.11',    'Indemnización por Desahucio',                     'EGRESO',     'D', NULL),
('5.2.1.12',    'Provisión Vacaciones',                            'EGRESO',     'D', 'Gasto devengado mensualmente'),
('5.2.1.13',    'Capacitación SENCE',                              'EGRESO',     'D', 'Crédito fiscal hasta 1% remuneraciones imponibles'),
('5.2.1.14',    'Beneficios Adicionales al Personal',              'EGRESO',     'D', 'Colación, movilización, sala cuna, etc.'),
('5.2.2',       'GASTOS GENERALES DE ADMINISTRACIÓN',              'EGRESO',     'A', NULL),
('5.2.2.01',    'Arriendos de Oficinas y Bodegas',                 'EGRESO',     'D', 'Afectos IVA si arrendador es contribuyente'),
('5.2.2.02',    'Gastos Comunes y Mantención Instalaciones',       'EGRESO',     'D', NULL),
('5.2.2.03',    'Servicios Básicos (Agua, Luz, Gas, Internet)',    'EGRESO',     'D', NULL),
('5.2.2.04',    'Telecomunicaciones y Telefonía',                  'EGRESO',     'D', NULL),
('5.2.2.05',    'Materiales de Oficina y Computación',             'EGRESO',     'D', NULL),
('5.2.2.06',    'Seguros',                                         'EGRESO',     'D', 'Incendio, robo, RC, vida clave'),
('5.2.2.07',    'Contribuciones de Bienes Raíces',                 'EGRESO',     'D', 'Gasto tributario si no uso habitacional'),
('5.2.2.08',    'Patente Municipal',                               'EGRESO',     'D', 'Tasa 2,5‰ a 5‰ del capital propio tributario'),
('5.2.2.09',    'Gastos Notariales y Legales',                     'EGRESO',     'D', NULL),
('5.2.2.10',    'Honorarios Profesionales Externos',               'EGRESO',     'D', 'Contador, abogado, consultor'),
('5.2.2.11',    'Servicios de Contabilidad Externalizados',        'EGRESO',     'D', NULL),
('5.2.2.12',    'Auditoría Externa',                               'EGRESO',     'D', NULL),
('5.2.2.13',    'Tecnología y Software (SaaS, licencias)',         'EGRESO',     'D', NULL),
('5.2.2.14',    'Gastos de Viaje y Estadía',                       'EGRESO',     'D', 'Acreditar con documentación; límites razonables SII'),
('5.2.2.15',    'Gastos de Representación y Atención Clientes',    'EGRESO',     'D', 'Tope deducción tributaria 1,5% RLI o 15% GTF'),
('5.2.2.16',    'Publicidad y Marketing',                          'EGRESO',     'D', NULL),
('5.2.2.17',    'Imprenta y Reproducción',                         'EGRESO',     'D', NULL),
('5.2.2.18',    'Suscripciones y Membresías Gremiales',            'EGRESO',     'D', NULL),
('5.2.2.19',    'Donaciones (con Ley de Donaciones)',              'EGRESO',     'D', 'Ley 19.885; crédito hasta 50% donación, tope 4,5% RLI'),
('5.2.2.20',    'Gastos de Cobranza',                              'EGRESO',     'D', NULL),
('5.2.2.21',    'Gastos de Limpieza y Aseo',                       'EGRESO',     'D', NULL),
('5.2.2.22',    'Gastos de Seguridad',                             'EGRESO',     'D', NULL),
('5.2.3',       'GASTOS DE VENTAS Y COMERCIALES',                  'EGRESO',     'A', NULL),
('5.2.3.01',    'Fletes y Gastos de Distribución',                 'EGRESO',     'D', 'Afectos IVA si proveedor es transportista'),
('5.2.3.02',    'Comisiones a Agentes de Venta Externos',          'EGRESO',     'D', NULL),
('5.2.3.03',    'Gastos de Embalaje y Despacho',                   'EGRESO',     'D', NULL),
('5.2.3.04',    'Garantías y Devoluciones',                        'EGRESO',     'D', NULL),
('5.2.3.05',    'Gastos de Licitaciones y Propuestas',             'EGRESO',     'D', NULL),
('5.2.4',       'DEPRECIACIÓN Y AMORTIZACIÓN',                     'EGRESO',     'A', NULL),
('5.2.4.01',    'Depreciación PPE - Edificios',                    'EGRESO',     'D', 'VU normal o acelerada (art.31 N°5 bis LIR)'),
('5.2.4.02',    'Depreciación PPE - Maquinaria y Equipos',         'EGRESO',     'D', 'Depreciación acelerada: 1/3 VU normal'),
('5.2.4.03',    'Depreciación PPE - Vehículos',                    'EGRESO',     'D', NULL),
('5.2.4.04',    'Depreciación PPE - Muebles y Enseres',            'EGRESO',     'D', NULL),
('5.2.4.05',    'Depreciación PPE - Equipos Computación',          'EGRESO',     'D', NULL),
('5.2.4.06',    'Depreciación PPE - Otros',                        'EGRESO',     'D', NULL),
('5.2.4.07',    'Amortización Intangibles',                        'EGRESO',     'D', NULL),
('5.2.4.08',    'Amortización Goodwill',                           'EGRESO',     'D', 'NIIF PyME: 10 años si VU no estimable'),
('5.2.5',       'GASTOS FINANCIEROS',                              'EGRESO',     'A', NULL),
('5.2.5.01',    'Intereses Pagados - Deudas Bancarias',            'EGRESO',     'D', 'Gasto tributario art.31 N°1; atención exceso endeudamiento'),
('5.2.5.02',    'Intereses Leasing Financiero',                    'EGRESO',     'D', NULL),
('5.2.5.03',    'Comisiones Bancarias',                            'EGRESO',     'D', NULL),
('5.2.5.04',    'Gastos de Factoring',                             'EGRESO',     'D', NULL),
('5.2.5.05',    'Impuesto de Timbres y Estampillas',               'EGRESO',     'D', 'Art.1 DL3.475; gasto tributario'),
('5.2.5.06',    'Diferencias de Cambio Desfavorables',             'EGRESO',     'D', NULL),
('5.2.5.07',    'Pérdida en Instrumentos Financieros',             'EGRESO',     'D', NULL),
('5.2.6',       'GASTOS TRIBUTARIOS NO DEDUCIBLES (RECHAZADOS)',   'EGRESO',     'A', 'NIIF PyME S.29; diferencias permanentes'),
('5.2.6.01',    'Gastos Rechazados art.21 LIR - Afectos Imp.35%', 'EGRESO',     'D', 'Impuesto único 35% SA/SpA; o IGC/IA socios'),
('5.2.6.02',    'Multas y Sanciones Fiscales (SII, Tesorería)',    'EGRESO',     'D', 'No deducible tributariamente art.31'),
('5.2.6.03',    'Multas Laborales (DT)',                           'EGRESO',     'D', 'No deducible'),
('5.2.6.04',    'IVA sin derecho a CF (crédito irrecuperable)',    'EGRESO',     'D', 'Ej. vehículos art.23 N°6; gastos recreativos'),
('5.2.6.05',    'Otros Gastos No Deducibles',                      'EGRESO',     'D', NULL),
('5.2.7',       'DETERIORO Y CASTIGOS',                            'EGRESO',     'A', NULL),
('5.2.7.01',    'Deterioro de Cuentas por Cobrar (Castigo)',       'EGRESO',     'D', 'Art.31 N°4 LIR; requisitos: agotamiento cobro'),
('5.2.7.02',    'Deterioro de Inventarios',                        'EGRESO',     'D', 'Acreditar con informe técnico'),
('5.2.7.03',    'Deterioro de Activos Fijos (NIIF PyME S.27)',    'EGRESO',     'D', NULL),
('5.2.7.04',    'Pérdida en Baja de Activos Fijos',               'EGRESO',     'D', 'VNT menos precio venta si negativo'),
('5.3',         'IMPUESTO A LA RENTA',                             'EGRESO',     'A', 'NIIF PyME Sección 29'),
('5.3.1.01',    'Gasto por Impuesto de Primera Categoría',         'EGRESO',     'D', 'Tasa 27% SA/SpA Semi Integrado; 25% régimen propyme'),
('5.3.1.02',    'Gasto por Impuesto Diferido',                     'EGRESO',     'D', 'Originación y reversión diferencias temporarias'),
('5.4',         'CORRECCIÓN MONETARIA PASIVOS Y PATRIMONIO',       'EGRESO',     'A', NULL),
('5.4.1.01',    'Corrección Monetaria Pasivos/Patrimonio (IPC)',   'EGRESO',     'D', 'Art.41 LIR; contrapartida corrección monetaria'),

-- CLASE 9: CUENTAS DE ORDEN
('9',           'CUENTAS DE ORDEN',                                'ORDEN',      'A', 'Memorándum; no afectan resultados ni balance'),
('9.1.1.01',    'Avales y Garantías Otorgadas',                    'ORDEN',      'D', 'Registrar para control y revelación en notas'),
('9.1.1.02',    'Avales y Garantías Recibidas',                    'ORDEN',      'D', NULL),
('9.1.2.01',    'Bienes de Terceros en Custodia',                  'ORDEN',      'D', NULL),
('9.1.2.02',    'Bienes Propios en Poder de Terceros',             'ORDEN',      'D', NULL),
('9.1.3.01',    'Contratos de Arriendo Operativo (compromisos)',   'ORDEN',      'D', 'Revelar en notas NIIF PyME S.20'),
('9.1.3.02',    'Boletas de Garantía Emitidas',                    'ORDEN',      'D', NULL),
('9.1.3.03',    'Litigios y Contingencias Pasivas',               'ORDEN',      'D', 'Si posible pero no probable; solo revelar');
